# Generated by Django 3.2.12 on 2024-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='заголовок')),
                ('title2', models.CharField(max_length=500, verbose_name='второе слово заголовка')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'заголовок',
            },
        ),
    ]
