# Generated by Django 3.2.12 on 2024-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerstBlvariors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='первый блок 4секции заголовок')),
                ('network_image', models.ImageField(blank=True, upload_to='image_ferst_block', verbose_name='картинка первого блока')),
            ],
            options={
                'verbose_name': 'первый блок 4 секции',
                'verbose_name_plural': 'первый блок 4 секции',
            },
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'домашняя', 'verbose_name_plural': 'домашняя'},
        ),
        migrations.AddField(
            model_name='home',
            name='pod_title2',
            field=models.CharField(default=1, max_length=255, verbose_name='текст под заголовком'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=255, verbose_name='заголовок'),
        ),
    ]
