# Generated by Django 3.2.12 on 2024-03-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0002_auto_20240302_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferstblvariors',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ferstphoto', to='landingspin.home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferstblvariors',
            name='title2',
            field=models.CharField(blank=True, max_length=255, verbose_name='меньший текст под фото'),
        ),
        migrations.AlterField(
            model_name='ferstblvariors',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='первый блок 4секции заголовок'),
        ),
    ]
