# Generated by Django 3.2.12 on 2024-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0003_auto_20240302_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='титл о нас')),
                ('title2', models.CharField(max_length=255, verbose_name='текст под титл')),
                ('onasimage', models.ImageField(blank=True, upload_to='image_onas', verbose_name='картинка онас')),
                ('title3', models.CharField(max_length=255, verbose_name='титл три')),
                ('title4', models.CharField(max_length=255, verbose_name='титл четыре')),
                ('title5', models.TextField(blank=True, verbose_name='текст')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onas', to='landingspin.home')),
            ],
            options={
                'verbose_name': 'о нас',
                'verbose_name_plural': 'о нас',
            },
        ),
    ]
