# Generated by Django 3.2.12 on 2024-03-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0004_onas'),
    ]

    operations = [
        migrations.AddField(
            model_name='onas',
            name='title6',
            field=models.TextField(blank=True, verbose_name='текст описание'),
        ),
    ]
