# Generated by Django 3.2.12 on 2024-03-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0006_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='for',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fort', to='landingspin.home'),
            preserve_default=False,
        ),
    ]
