# Generated by Django 3.2.12 on 2024-03-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0007_for_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Five',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='5 заголовок')),
                ('title2', models.CharField(max_length=500, verbose_name='5 текст под титл')),
                ('image', models.ImageField(blank=True, upload_to='5class', verbose_name='фото 5 блока')),
                ('text5', models.TextField(blank=True, verbose_name='5 блок текст описание')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five', to='landingspin.home')),
            ],
            options={
                'verbose_name': 'четвёртый блок',
                'verbose_name_plural': 'четвёртый блок',
            },
        ),
    ]
