# Generated by Django 3.2.12 on 2024-03-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0008_five'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='five',
            options={'verbose_name': 'пятый блок', 'verbose_name_plural': 'пятый блок'},
        ),
        migrations.CreateModel(
            name='SexBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='6 блок')),
                ('network_image', models.ImageField(blank=True, upload_to='image_6_block', verbose_name='картинка 6 блока')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sexblock', to='landingspin.home')),
            ],
            options={
                'verbose_name': 'шестой блок',
                'verbose_name_plural': 'шестой блок',
            },
        ),
        migrations.CreateModel(
            name='PodSexBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='под 6 title')),
                ('text', models.TextField(blank=True, verbose_name='текст под 6 блоком')),
                ('sexblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_sexblock', to='landingspin.sexblock')),
            ],
            options={
                'verbose_name': 'текст под шестой блок',
                'verbose_name_plural': 'текст под шестой блок',
            },
        ),
    ]
