# Generated by Django 3.2.12 on 2024-03-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0009_auto_20240303_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='podsexblock',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_pod_6_block', verbose_name='картинка_под_6'),
        ),
    ]
