# Generated by Django 3.2.12 on 2024-03-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0010_podsexblock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexblock',
            name='title1',
            field=models.CharField(blank=True, max_length=255, verbose_name='6 блокпод фото'),
        ),
        migrations.AddField(
            model_name='sexblock',
            name='title2',
            field=models.CharField(blank=True, max_length=500, verbose_name='6 блок текст'),
        ),
        migrations.DeleteModel(
            name='PodSexBlock',
        ),
    ]
