# Generated by Django 3.2.12 on 2024-03-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0011_auto_20240304_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.CharField(max_length=500, verbose_name='вопрос')),
                ('body_question', models.TextField(blank=True, default='', verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'вопросы',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.AlterField(
            model_name='sexblock',
            name='title1',
            field=models.CharField(blank=True, max_length=500, verbose_name='6 блокпод фото'),
        ),
    ]
