# Generated by Django 3.2.12 on 2024-03-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0012_auto_20240304_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='landingspin.home'),
            preserve_default=False,
        ),
    ]
