# Generated by Django 3.2.12 on 2024-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0014_category_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
