# Generated by Django 3.2.12 on 2024-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0016_auto_20240304_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=500, verbose_name='title1')),
                ('title2', models.CharField(max_length=500, verbose_name='title2')),
                ('title3', models.CharField(max_length=500, verbose_name='title3')),
                ('location', models.CharField(max_length=500, verbose_name='адрес')),
                ('email', models.CharField(max_length=500, verbose_name='email')),
                ('tel', models.CharField(max_length=500, verbose_name='tel')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
