# Generated by Django 3.2.12 on 2024-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0017_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('title1', models.CharField(max_length=500, verbose_name='title1')),
                ('title2', models.CharField(max_length=500, verbose_name='title2')),
                ('title3', models.CharField(max_length=500, verbose_name='title3')),
                ('title4', models.CharField(max_length=500, verbose_name='title4')),
                ('title5', models.CharField(max_length=500, verbose_name='title5')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
    ]
