# Generated by Django 3.2.12 on 2024-03-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0018_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='for',
            name='image',
            field=models.ImageField(blank=True, upload_to='for', verbose_name='фото for'),
        ),
    ]
