# Generated by Django 3.2.12 on 2024-03-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingspin', '0020_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FerstBlvariors',
        ),
    ]
